[package]
name = "zenertest-cracker"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
reqwest = { version = "0.12.23", features = ["cookies", "json"] }
serde = { version = "1.0.226", features = ["derive"] }
tokio = { version = "1.47.1", features = ["full"] }
